theme: jekyll-theme-architect

title: [mq-tech-over]
description: [Eclipse Open Message Queue Technical Overview, Release 5.0]

# sidebar links url
links:
  source: https://github.com/javaee/mq-tech-over
  download: https://github.com/javaee/mq-tech-over/releases
  #mailinglist: https://javaee.groups.io/g/mq-tech-over
  #javadocs:
  docs: https://javaee.github.io/mq-tech-over
  #faq:

