theme: jekyll-theme-architect

title: [mq-admin-guide]
description: [Eclipse Open Message Queue Administration Guide, Release 5.0]

# sidebar links url
links:
  source: https://github.com/javaee/mq-admin-guide
  download: https://github.com/javaee/mq-admin-guide/releases
  #mailinglist: https://javaee.groups.io/g/mq-admin-guide
  #javadocs:
  docs: https://javaee.github.io/mq-admin-guide
  #faq:

